# Generated by Django 4.1.1 on 2022-09-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_location_group_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(to='groups.student'),
        ),
    ]
