# Generated by Django 4.1.1 on 2022-09-28 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_curso_group_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='disciplina',
            field=models.ManyToManyField(to='groups.disciplina'),
        ),
        migrations.AddField(
            model_name='group',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.disciplina'),
            preserve_default=False,
        ),
    ]
