# Generated by Django 4.1.1 on 2022-09-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_disciplina_curso_disciplina_group_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='student',
            field=models.ManyToManyField(to='groups.student'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='student',
            field=models.ManyToManyField(to='groups.student'),
        ),
    ]
