# Generated by Django 4.1.1 on 2022-09-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_curso_student_disciplina_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(to='groups.messages'),
        ),
    ]
