# Generated by Django 4.1.1 on 2022-09-28 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_remove_group_messages_messages_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alunos', models.ManyToManyField(to='groups.student')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.location')),
            ],
        ),
    ]
