# Generated by Django 4.0.5 on 2022-11-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_remove_question_tag_question_student_tag_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('1', 'Muito Pouco'), ('2', 'Pouco'), ('3', 'Neutro'), ('4', 'Concordo'), ('5', 'Bastante')], max_length=1, verbose_name='Agree')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.question')),
            ],
        ),
    ]
