# Generated by Django 4.1.1 on 2022-10-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='groups.student'),
        ),
    ]
