# Generated by Django 4.0.5 on 2022-11-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_alter_question_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='student',
            field=models.ManyToManyField(blank=True, to='groups.student'),
        ),
    ]
